[package]
name = "similarium"
description = "A slack bot to play Similarium together"
homepage = "https://similarium.dev"
authors = ["Axel <similarium@absalon.dev>"]
version = "0.0.1"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/ikornaselur/similarium-rs"

[dependencies]
actix-web = "4.2"
anyhow = "1.0"
dotenvy = "0.15"
env_logger = "0.9"
log = "0.4"
mt19937 = "2.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
sqlx = { version = "0.6", features = ["sqlite", "runtime-actix-rustls"] }
