[package]
name = "similarium"
description = "A slack bot to play Similarium together"
homepage = "https://similarium.dev"
authors = ["Axel <similarium@absalon.dev>"]
version = "0.0.1"
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/ikornaselur/similarium-rs"

[dependencies]
actix-web = "4"
anyhow = "1"
awc = { version = "3", features = ["rustls"] }
dotenvy = "0.15"
env_logger = "0.10"
log = "0.4"
mt19937 = "2.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls", "uuid", "chrono"] }
