FROM rust:1.75-buster AS builder
WORKDIR /usr/src
RUN apt-get update -y && apt-get install musl-tools ca-certificates -y
RUN rustup target add x86_64-unknown-linux-musl

RUN USER=root cargo new similarium
WORKDIR /usr/src/similarium

COPY Cargo.toml Cargo.lock ./
RUN cargo build --target x86_64-unknown-linux-musl --bin similarium

COPY src ./src
COPY .sqlx ./.sqlx
COPY migrations ./migrations
COPY build.rs ./
RUN cargo build --target x86_64-unknown-linux-musl --bin similarium

FROM scratch
 
COPY --from=builder /usr/src/similarium/target/x86_64-unknown-linux-musl/debug/similarium .
COPY --from=builder /etc/ssl /etc/ssl
USER 1000
EXPOSE 8080
 
CMD ["./similarium"]
