on: [push]

name: Tast and lint

jobs:
  build:
    name: Build and cache project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "run"

      - name: Build project
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo build

      - name: Cargo check to build a check cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo check
        
  check:
    name: Check
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "run"

      - name: Run cargo check
        run: cargo check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "run"

      - name: Run cargo test
        run: cargo test

  lints:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "run"

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
